Repository openEHR/archie, pull requests merged in 2021-11, with the labels that each got.

#364 Add missing setThisAsParent for the description of an Activity
  openehr-rm/src/main/java/com/nedap/archie/rm/composition/Activity.java
Labels: bug

#365 Update README.md to point to new version
  README.md
Labels: enhancement

#313 Json schema v2
  bmm/src/main/java/org/openehr/bmm/core/BmmPackage.java
  bmm/src/main/java/org/openehr/bmm/v2/validation/converters/BmmModelCreator.java
  json-schema/README.md
  json-schema/build.gradle
  json-schema/settings.gradle
  tools/build.gradle
  tools/src/main/java/com/nedap/archie/creation/ExampleJsonInstanceGenerator.java
  tools/src/main/java/com/nedap/archie/json/ItsJsonUriProvider.java
  tools/src/main/java/com/nedap/archie/json/JSONSchemaCreator.java
  tools/src/main/java/com/nedap/archie/json/JsonSchemaUri.java
  tools/src/main/java/com/nedap/archie/json/JsonSchemaUriProvider.java
  tools/src/main/java/com/nedap/archie/json/JsonSchemaValidator.java
  tools/src/test/java/com/nedap/archie/creation/ExampleJsonInstanceGeneratorTest.java
  tools/src/test/java/com/nedap/archie/json/JSONSchemaCreatorTest.java
Labels: ready for review
